# Generated by Django 2.2.4 on 2021-03-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredprogramscheckins',
            name='progress',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
