# Generated by Django 2.2.4 on 2021-03-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_registeredprogramscheckins_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredprogramscheckins',
            name='tag',
            field=models.CharField(default='bug', max_length=100),
            preserve_default=False,
        ),
    ]
