# Generated by Django 2.2.4 on 2021-03-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_devnotice_devnoticecheckins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='devNotice',
            new_name='RegistereddevNotice',
        ),
    ]
